### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by minibikini** [almightycouch/rethinkdb_ecto#17]
Hi @almightycouch, 
I get compilation error for rethinkdb_ecto:

```sh
$  mix deps.clean rethinkdb_ecto
* Cleaning rethinkdb_ecto

$ mix deps.get rethinkdb_ecto                                                                                                       
Running dependency resolution
* Getting rethinkdb_ecto (Hex package)
  Checking package (https://repo.hex.pm/tarballs/rethinkdb_ecto-0.5.0.tar)
  Using locally cached package

$ mix deps.compile rethinkdb_ecto                                                                                                    
==> rethinkdb_ecto
Compiling 2 files (.ex)

== Compilation error on file lib/rethinkdb_ecto/normalized_query.ex ==
** (CompileError) lib/rethinkdb_ecto/normalized_query.ex:8: module RethinkDB.Lambda is not loaded and could not be found
could not compile dependency :rethinkdb_ecto, "mix compile" failed. You can recompile this dependency with "mix deps.compile rethinkdb_ecto", update it with "mix deps.update rethinkdb_ecto" or clean it with "mix deps.clean rethinkdb_ecto"
```

Elixir version:
```
Erlang/OTP 19 [erts-8.0.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.2
```

I have [rethinkdb](https://hex.pm/packages/rethinkdb) driver installed on my machine, may be this is the reason?

**Comment by StephanMeijer** [comment]
You are not the only one having this error.

`mix --version`

```
Erlang/OTP 19 [erts-8.0.2] [source-753b9b9] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Mix 1.3.1
```

`elixir --version`

```
Erlang/OTP 19 [erts-8.0.2] [source-753b9b9] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.3.1
```

`erl --version`

```
Erlang/OTP 19 [erts-8.0.2] [source-753b9b9] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.0.2  (abort with ^G)
```

**Comment by almightycouch** [comment]
Hi @minibikini, @StephanMeijer.

You got this compilation error because you are using the latest version published on Hex which uses a fork of the `:rethinkdb` package to use `DBConnection` instead of `Connection`.

Hex does not support GitHub dependencies and you would have to add `:rethinkdb`'s fork to your dependencies.

```elixir
def deps do
  [{:rethinkdb_ecto, "~> 0.5"},
   {:rethinkdb, github: "almightycouch/rethinkdb-elixir"}]
end
```

But, after a lot of refactoring and a [long discussion](https://github.com/hamiltop/rethinkdb-elixir/pull/106) with @hamiltop (author of `:rethinkdb`) and @fishcakez (author of `:db_connection`), we decided not to merge the changes into mainstream.

I will refactor a lot of the current code to support Ecto 2.x using the actual `:rethinkdb` package. In the meantime, you should consider downgrading to version `0.4` which is compatible with Ecto 1.x:

```elixir
def deps do
  [{:rethinkdb_ecto, "~> 0.4"}]
end
```

If you really want to have support for Ecto 2.x, you can check-out the [`ecto_2` branch](https://github.com/almightycouch/rethinkdb_ecto/tree/ecto_2). Which actually has some flaws...

**Comment by minibikini** [comment]
Thanks @almightycouch !
